In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
rat=pd.read_csv('ratings.csv')

In [40]:
rat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26024289 entries, 0 to 26024288
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   userId   int64
 1   movieId  int64
 2   rating   float64
dtypes: float64(1), int64(2)
memory usage: 595.6 MB

In [56]:
t=rat.groupby('userId').mean()['rating'].reset_index()

In [53]:
f_users=t[t['rating']>500]

In [55]:
f_users.rename(columns={'rating':'num_rating'},inplace=True)

C:\Users\prateek\AppData\Local\Temp\ipykernel_1168\2163830920.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_users.rename(columns={'rating':'num_rating'},inplace=True)

In [58]:
f_users

      userId  num_rating    rating
0         24         634  3.474763
1         46         766  3.210836
2        120         516  3.488372
3        132         572  3.375874
4        150         585  3.167521
...      ...         ...       ...
9447  270654        2297  3.489334
9448  270684         729  3.205761
9449  270734         733  3.881310
9450  270769         733  3.297408
9451  270887        2501  3.644142

[9452 rows x 3 columns]

In [57]:
f_users=f_users.merge(t,on='userId')

In [66]:
rating_with_users=rat[rat['userId'].isin(f_users['userId'])]

In [69]:
rating_with_users=rating_with_users.reset_index(drop=True)

In [70]:
rating_with_users

         userId  movieId  rating
0            24        1     4.0
1            24        2     3.0
2            24        6     4.0
3            24       16     3.0
4            24       17     3.0
...         ...      ...     ...
8543114  270887   171439     1.0
8543115  270887   171755     3.0
8543116  270887   173149     5.0
8543117  270887   173405     5.0
8543118  270887   174473     5.0

[8543119 rows x 3 columns]

## working on popular movies

In [71]:
df=pd.read_csv('movies_metadata.csv')

C:\Users\prateek\AppData\Local\Temp\ipykernel_1168\2212646091.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('movies_metadata.csv')

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [82]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [83]:
columns_to_select = ['id', 'title', 'original_language', 'vote_average', 'vote_count','popularity','poster_path']
selected_columns_df = df[columns_to_select]

In [87]:
selected_columns_df['popularity']=pd.to_numeric(selected_columns_df['popularity'],errors='coerce')

C:\Users\prateek\AppData\Local\Temp\ipykernel_1168\1096959785.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_columns_df['popularity']=pd.to_numeric(selected_columns_df['popularity'],errors='coerce')

In [176]:
sc_df=selected_columns_df[(selected_columns_df['popularity']>12) & (selected_columns_df['vote_count']>50)].reset_index().sort_values('vote_count',ascending=False)

In [179]:
sc_df.drop('index',axis=1,inplace=True)

In [191]:
sc_df['movieId']=pd.to_numeric(sc_df['movieId'],errors='coerce')

In [192]:
sc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1608 entries, 0 to 1607
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   movieId            1608 non-null   int64
 1   title              1608 non-null   object
 2   original_language  1608 non-null   object
 3   vote_average       1608 non-null   float64
 4   vote_count         1608 non-null   float64
 5   popularity         1608 non-null   float64
 6   poster_path        1608 non-null   object
 7   id                 1608 non-null   int64
dtypes: float64(3), int64(2), object(3)
memory usage: 100.6+ KB

In [180]:
sc_df.rename(columns={'id':'movieId'},inplace=True)

In [178]:
sc_df.reset_index(inplace=True,drop=True)

In [217]:
pp=sc_df.head(50)

In [ ]:
pp.to_csv('popular_movies.csv',index=False)

In [189]:
rf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41894 entries, 17 to 8540742
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   userId   41894 non-null  int64
 1   movieId  41894 non-null  int64
 2   rating   41894 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 1.3 MB

In [127]:
rf

         userId  movieId  rating
17           24       58     5.0
81           24      550     2.0
93           24      597     3.0
640          46       24     3.0
652          46      105     1.5
...         ...      ...     ...
8540642  270887      105     5.0
8540718  270887      539     5.0
8540731  270887      597     5.0
8540735  270887      637     3.0
8540742  270887      673     1.0

[41894 rows x 3 columns]

In [209]:
sc_df.nunique()

movieId              1607
title                1583
original_language      18
vote_average           46
vote_count           1185
popularity           1607
poster_path          1607
id                   1607
dtype: int64

In [193]:
data=sc_df.merge(rf,on='movieId')

In [194]:
pt=data.pivot_table(columns='userId',index='title',values='rating')

In [203]:
pt

userId,24,46,120,132,150,229,231,251,332,340,...,270551,270555,270564,270579,270631,270654,270684,270734,270769,270887
title,,,,,,,,,,,,,,,,,,,,,
Ant-Man,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Avengers: Age of Ultron,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Back to the Future,NaN,1.5,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,NaN,3.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,5.0
Batman Begins,NaN,NaN,4.0,4.0,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Blade Runner,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dawn of the Planet of the Apes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fight Club,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Finding Nemo,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Forrest Gump,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Guardians of the Galaxy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Harry Potter and the Chamber of Secrets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Harry Potter and the Philosopher's Stone,NaN,2.5,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
Harry Potter and the Prisoner of Azkaban,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,0.5,NaN,3.0,NaN,NaN,1.0
Inception,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Interstellar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kill Bill: Vol. 1,NaN,3.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
Life Is Beautiful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
"Monsters, Inc.",NaN,NaN,3.5,NaN,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,3.0,NaN,NaN
Once Upon a Time in America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
One Flew Over the Cuckoo's Nest,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Pan's Labyrinth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN
Pirates of the Caribbean: At World's End,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Pirates of the Caribbean: Dead Man's Chest,5.0,NaN,3.5,NaN,NaN,NaN,NaN,NaN,NaN,3.0,...,NaN,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN
Pirates of the Caribbean: On Stranger Tides,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN
Pirates of the Caribbean: The Curse of the Black Pearl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.0,3.0,2.5,3.0,NaN,NaN,4.0,NaN,4.5
Psycho,NaN,NaN,3.5,NaN,2.0,1.0,NaN,NaN,NaN,3.5,...,3.0,3.0,2.5,NaN,NaN,NaN,4.0,5.0,3.0,5.0
Pulp Fiction,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
Schindler's List,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
Spider-Man 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Spirited Away,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Star Wars,NaN,NaN,NaN,3.0,3.0,NaN,NaN,NaN,NaN,3.5,...,NaN,3.0,NaN,3.0,NaN,4.0,4.0,5.0,NaN,4.0
The Amazing Spider-Man,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
The Dark Knight,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
The Godfather,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
The Godfather: Part II,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
The Hunger Games: Catching Fire,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
The Hunger Games: Mockingjay - Part 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
The Lord of the Rings: The Fellowship of the Ring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
The Lord of the Rings: The Return of the King,NaN,3.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
The Lord of the Rings: The Two Towers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
The Matrix,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
The Shawshank Redemption,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
The Twilight Saga: Breaking Dawn - Part 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Titanic,3.0,NaN,3.0,NaN,NaN,2.0,3.0,3.0,2.5,NaN,...,1.5,NaN,3.5,3.5,3.0,4.0,4.0,4.0,4.0,5.0
Twilight,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,NaN,3.5,3.0,NaN,NaN,NaN,NaN
X-Men: Days of Future Past,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [216]:
import pickle
pickle.dump(pt,open('pt.pkl','wb'))

In [149]:
from sklearn.metrics.pairwise import cosine_similarity
simi=cosine_similarity(pt.fillna(0))

In [150]:
import pickle
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(simi,open('simi.pkl','wb'))

In [211]:
def recommend(movie):
    index=np.where(pt.index==movie)[0][0]
    s=sorted(list(enumerate(simi[index])),key=lambda x:x[1],reverse=True)[1:6]
   
    for i in s:
        print(pt.index[i[0]])

In [214]:
recommend('The Hunger Games: Mockingjay - Part 2')

Schindler's List
Twilight
The Lord of the Rings: The Return of the King
Harry Potter and the Prisoner of Azkaban
Monsters, Inc.

In [2]:
f=pd.read_csv('movies_metadata.csv')

C:\Users\prateek\AppData\Local\Temp\ipykernel_1708\2551636135.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  f=pd.read_csv('movies_metadata.csv')

In [6]:
f=f[['title','id']]

In [36]:
r.to_csv('movie_name_id.csv',index=False)

In [24]:
t=pd.to_numeric(f['id'],errors='coerce')

In [26]:
f['id']=t

C:\Users\prateek\AppData\Local\Temp\ipykernel_1708\3769735715.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f['id']=t

In [28]:
int(f[f['title']=='Inception']['id'].values[0])

27205

In [37]:
r=pd.read_csv('movie_name_id.csv')

In [38]:
r

                             title      id
0                        Toy Story     862
1                          Jumanji    8844
2                 Grumpier Old Men   15602
3                Waiting to Exhale   31357
4      Father of the Bride Part II   11862
...                            ...     ...
45461                       Subdue  439050
45462          Century of Birthing  111109
45463                     Betrayal   67758
45464             Satan Triumphant  227506
45465                     Queerama  461257

[45466 rows x 2 columns]

In [40]:
import pickle
pt=pickle.load(open('pt.pkl','rb'))

In [41]:
pt.index

Index(['Ant-Man', 'Avengers: Age of Ultron', 'Back to the Future',
       'Batman Begins', 'Blade Runner', 'Dawn of the Planet of the Apes',
       'Fight Club', 'Finding Nemo', 'Forrest Gump', 'Guardians of the Galaxy',
       'Harry Potter and the Chamber of Secrets',
       'Harry Potter and the Philosopher's Stone',
       'Harry Potter and the Prisoner of Azkaban', 'Inception', 'Interstellar',
       'Kill Bill: Vol. 1', 'Life Is Beautiful', 'Monsters, Inc.',
       'Once Upon a Time in America', 'One Flew Over the Cuckoo's Nest',
       'Pan's Labyrinth', 'Pirates of the Caribbean: At World's End',
       'Pirates of the Caribbean: Dead Man's Chest',
       'Pirates of the Caribbean: On Stranger Tides',
       'Pirates of the Caribbean: The Curse of the Black Pearl', 'Psycho',
       'Pulp Fiction', 'Schindler's List', 'Spider-Man 3', 'Spirited Away',
       'Star Wars', 'The Amazing Spider-Man', 'The Dark Knight',
       'The Godfather', 'The Godfather: Part II',
       'The Hunger Games: Catching Fire',
       'The Hunger Games: Mockingjay - Part 2',
       'The Lord of the Rings: The Fellowship of the Ring',
       'The Lord of the Rings: The Return of the King',
       'The Lord of the Rings: The Two Towers', 'The Matrix',
       'The Shawshank Redemption', 'The Twilight Saga: Breaking Dawn - Part 1',
       'Titanic', 'Twilight', 'X-Men: Days of Future Past'],
      dtype='object', name='title')

In [39]:
int(r[r['title']=='Jumanji']['id'].values[0])

8844